### ISSUE TITLE
Random seeds？

### ISSUE THREAD

**Issue by njuyuan** [EnyanDai/NRGNN#1]
Random seeds have a great impact on the performance of the model. When I remove the fixed random seeds, the performance of the model decreases significantly. 
For example, runs = 10
noise=uniform dataset=cora acc = 0.7743±0.0099, 
noise=pair dataset=cora acc=0.7538±0.0136, 
noise=uniform dataset=pubmed acc=0.7385±0.0115, 
noise=uniform dataset=pubmed acc = 0.7850±0.0155.
Can you publish more experimental details and relevant codes of contrast models?

**Comment by EnyanDai** [comment]
Hi, 
When you remove the fixed random seeds, do you also remove the seeds for generating noisy labels? The performance can varies a lot if different noises are added to the labels.
I have re-run the experiments by varying the random seeds from 10 to 15 on Cora.  The results match well with the paper. Here are more detailed results:

| seed    | 10    | 11    | 12    | 13    | 14    | 15    |
|---------|-------|-------|-------|-------|-------|-------|
| Uniform | 79.83 | 80.08 | 79.93 | 79.78 | 80.48 | 79.07 |
| Pair    | 79.02 | 78.77 | 79.33 | 79.48 | 78.42 | 78.82 |

**Comment by njuyuan** [comment]
Thank you. It would be better if you could provide the code of comparison models, which will greatly promote the research in this field.
